modLoader = "kotlinforforge"
loaderVersion = "[3.12.0,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Eureka/issues"
license = "Apache-2.0"

[[mods]]
modId = "vs_eureka"
version = "1.6.1"
displayName = "VS Eureka Mod"
authors = ["Tri0de", "ewoudje", "millennIumAMbiguity", "VS2 Discord Artists"]
description = '''
Basically Archimedes Ships, but with VS2 as the backend!
'''
logoFile = "icon.png"

[[dependencies.vs_eureka]]
modId = "forge"
mandatory = true
versionRange = "[47.0.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_eureka]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.4.5,)"
ordering = "AFTER"
side = "BOTH"